export const ROUTES = {
  HOME: '/',
  BLOGS: '/blogs',
  TRENDING: '/trending',
  TOPICS: '/topics',
  WRITERS: '/writers',
  ABOUT: '/about',
  CAREERS: '/careers',
  CONTACT: '/contact',
  DOCS: '/docs',
  API: '/api',
  FAQ: '/faq',
  PROFILE: '/profile',
  STORIES: '/stories',
  SETTINGS: '/settings',
  LOGOUT: '/logout',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  HELP: '/help',
  CREATE_POST: '/posts/create',
} as const;
